export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST ='LOGIN_REQUEST';
export const LOGOUT_REQUEST ='LOGOUT_REQUEST';
export const LOGIN_FAILURE ='LOGIN_FAILURE';
export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS';
export const LOGOUT_FAILURE ='LOGOUT_FAILURE';
export const HOLDS_SUCCESS= 'HOLDS_SUCCESS';
export const HOLDS_FAILURE= 'HOLDS_FAILURE';
export const HOLDS_REQUEST= 'HOLDS_REQUEST';
export const HISTORY_REQUEST= 'HISTORY_REQUEST';
export const HISTORY_SUCCESS= 'HISTORY_SUCCESS';
export const HISTORY_FAILURE= 'HISTORY_FAILURE';
export const USER_FAILURE= 'USER_FAILURE';
export const USER_REQUEST= 'USER_REQUEST';
export const USER_SUCCESS= 'USER_SUCCESS';
export const CORP_LOADING = 'CORP_LOADING';
export const CORP_SUCCESS = 'CORP_SUCCESS';
export const CORP_FAILURE = 'CORP_FAILURE';
export const SHARE_LOADING = 'SHARE_LOADING';
export const SHARE_SUCCESS = 'SHARE_SUCCESS';
export const SHARE_FAILURE = 'SHARE_FAILURE';
export const MYSHARE_LOADING = 'MYSHARE_LOADING';
export const MYSHARE_SUCCESS = 'MYSHARE_SUCCESS';
export const MYSHARE_FAILURE = 'MYSHARE_FAILURE';
export const SALE_LOADING ='SALE_LOADING';
export const SALE_FAILED ='SALE_FAILED';
export const SALE_SUCCESS ='SALE_SUCCESS';
export const ACCOUNT_SUCCESS ='ACCOUNT_SUCCESS';
export const ACCOUNT_LOADING ='ACCOUNT_LOADING';
export const ACCOUNT_ERROR ='ACCOUNT_ERROR';
export const ADDMONEY_FAILED='ADDMONEY_FAILED';
export const COUNTRY_LOADING = 'COUNTRY_LOADING';
export const COUNTRY_SUCCESS = 'COUNTRY_SUCCESS';
export const COUNTRY_FAILURE = 'COUNTRY_FAILURE';
export const INSERT_CORP='INSERT_CORP';
export const INSERT_CORP_FAILURE='INSERT_CORP_FAILURE';







