export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST ='LOGIN_REQUEST';
export const LOGOUT_REQUEST ='LOGOUT_REQUEST';
export const LOGIN_FAILURE ='LOGIN_FAILURE';
export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS';
export const LOGOUT_FAILURE ='LOGOUT_FAILURE';
export const HOLDS_SUCCESS= 'HOLDS_SUCCESS';
export const HOLDS_FAILURE= 'HOLDS_FAILURE';
export const HOLDS_REQUEST= 'HOLDS_REQUEST';
export const HISTORY_REQUEST= 'HISTORY_REQUEST';
export const HISTORY_SUCCESS= 'HISTORY_SUCCESS';
export const HISTORY_FAILURE= 'HISTORY_FAILURE';
export const USER_FAILURE= 'USER_FAILURE';
export const USER_REQUEST= 'USER_REQUEST';
export const USER_SUCCESS= 'USER_SUCCESS';




